name: flutterexerciseapp
description: A new Flutter project.

version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: 0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Images.logo.png"

flutter:

  uses-material-design: true

  assets:
   - Images/background.png
   - Images/logo.png
   - Images/1.png
   - Images/2.png
   - Images/3.png
   - Images/4.png
   - Images/5.png
   - Images/6.png
   - Images/7.png
   - Images/8.png
   - Images/9.png
   - Images/10.png
   - Images/11.png
   - Images/12.png
   - Images/13.png
   - Images/14.png
   - Images/break.png
   - Images/createrImage.jpg
   - assets/

